environment:

  TOX_ENV: pywin

  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7.8
      PYTHON_ARCH: 32

#
#init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:

  #################################
  # Change Python Registry
  #################################

  - reg ADD HKCU\Software\Python\PythonCore\2.7\InstallPath /ve /d "C:\Python27" /t REG_SZ /f
  - reg ADD HKLM\Software\Python\PythonCore\2.7\InstallPath /ve /d "C:\Python27" /t REG_SZ /f

  #################################
  # Installing Inno Setup
  #################################

  - choco install -y InnoSetup
  - set PATH="C:\\Program Files (x86)\\Inno Setup 5";%PATH%

  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  - echo Upgrading pip...
  - ps: (new-object System.Net.WebClient).Downloadfile('https://bootstrap.pypa.io/get-pip.py', 'C:\Users\appveyor\get-pip.py')
  - ps: Start-Process -FilePath "C:\Python27\python.exe" -ArgumentList "C:\Users\appveyor\get-pip.py" -Wait -Passthru
  - pip --version
  - ps: |
      Set-Item WSMan:\localhost\Service\Auth\Basic $true
      Set-Item WSMan:\localhost\Service\AllowUnencrypted $true
      Invoke-Expression $($env:WITH_COMPILER + " pip install cffi coveralls")
      pip install .

      [Environment]::SetEnvironmentVariable("WINRM_ENDPOINT", "http://localhost:5985/wsman", "Machine")
      [Environment]::SetEnvironmentVariable("WINRM_USERNAME", $($env:USERNAME), "Machine")
      [Environment]::SetEnvironmentVariable("WINRM_PASSWORD", [Microsoft.Win32.Registry]::GetValue("HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon", "DefaultPassword", ''), "Machine")
      [Environment]::SetEnvironmentVariable("WINRM_TRANSPORT", "basic", "Machine")

  - pip install -r test-requirements.txt

build: false # Not a C# project, build stuff at the test step instead.

before_test:
  - echo Installing tox (2.0.0)
  - pip install tox==2.0.0

#on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:WINRM_ENDPOINT="http://localhost:5985/wsman"
      $env:WINRM_USERNAME=$($env:USERNAME)
      $env:WINRM_PASSWORD=[Microsoft.Win32.Registry]::GetValue("HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon", "DefaultPassword", '')
      $env:WINRM_TRANSPORT="basic"

  - tox -e %TOX_ENV%